language: cpp
dist: bionic
notifications:
  email: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CXX_COMPILER=g++-8; sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-8 800"


before_install:
  - eval "${MATRIX_EVAL}"
  - PARENTDIR=$(pwd)

install:
  - cd $PARENTDIR/build
  # Need lcov >= 1.14 for compatibility with g++ >= 8
  - wget http://downloads.sourceforge.net/ltp/lcov-1.14.tar.gz
  - tar zvxf lcov-1.14.tar.gz
  - export PATH=$(pwd)/lcov-1.14/bin/:${PATH}
  - cmake $PARENTDIR -DCMAKE_BUILD_TYPE:STRING=Debug -DBUILD_TESTING:BOOL=ON -DBUILD_COVERAGE:BOOL=ON -DBUILD_BENCHMARKING:BOOL=OFF -DCMAKE_CXX_COMPILER:FILEPATH=$CXX_COMPILER
  - make

script:
  - make coverage

after_success:
  - cd $PARENTDIR/build
  - lcov --list coverage.info  # Show test report in travis log.
  # Install coverals gem for uploading coverage to coveralls.
  - gem install coveralls-lcov
  - coveralls-lcov coverage.info  # uploads to coveralls
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
