environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    GENERATOR: "Visual Studio 16 2019"
    CONFIG: Debug

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    GENERATOR: "Visual Studio 16 2019"
    CONFIG: Release

matrix:
  fast_finish: true

build_script:
 - cmd: mkdir build
 - cmd: cd build
 - cmd: set PATH=C:\Program Files (x86)\CMake\bin;%PATH%
 - cmd: cmake --version
 - cmd: cmake .. -G"%GENERATOR%" -DCMAKE_BUILD_TYPE:STRING=%CONFIG% -DBUILD_TESTING:BOOL=ON -DBUILD_COVERAGE:BOOL=OFF -DBUILD_BENCHMARKING:BOOL=OFF
 - cmd: cmake --build . --config %CONFIG% --parallel
 - cmd: ctest --build-config %CONFIG% --output-on-failure
